module.exports = {
  //ACTIONS
  CONTACT: "CONTACT",
  LOAD: "LOAD",
  LOADING_COMPLEATE: "LOADING_COMPLEATE",
  CHANGE_STATE: "CHANGE_STATE",
  CHANGE_LANG: "CHANGE_LANG",
  //STATES
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
  LOADED: "LOADED",
  LOADING_CONTACT: "LOADING_CONTACT",
  LOADED_CONTACT: "LOADED_CONTACT",
  NOT_LOADED_CONTACT: "NOT_LOADED_CONTACT",
  VIEW: "VIEW",
  NOT_VIEW: "NOT_VIEW"
}
